[package]
name = "surge-ping"
version = "0.3.1"
authors = ["kolapapa <milk346512016@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/kolapapa/surge-ping"
description = "Asynchronous ICMP ping library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
log = "0.4.14"
parking_lot = "0.11.1"
pnet_packet = "0.28"
rand = "0.8.3"
socket2 = { git = "https://github.com/rust-lang/socket2.git" , features = ["all"] }
thiserror = "1.0"
tokio = { version = "1.7", features = ["time", "macros"] }

[dev-dependencies]
log = "0.4"
structopt = "0.3"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }

[[example]]
name = "simple"

[[example]]
name = "cmd"

[[example]]
name = "multi_ping"
